/**
 * 개발용 가짜 과목 데이터 (Mock Course Data)
 * 실제 API 연동 시 이 파일은 제거할 수 있음
 */

// ---------------------------------------------------------------------------
// 채플
// ---------------------------------------------------------------------------
export const MOCK_CHAPEL = {
  timestamp: '2026-02-06 01:29:27',
  result: [
    {
      category: 'CHAPEL' as const,
      subCategory: '인간',
      field: '인간',
      code: 99001001,
      name: '비전채플',
      professor: '김철홍',
      department: '공통',
      division: null,
      time: '1.0',
      point: '0.5',
      personeel: 0,
      scheduleRoom: '월 10:00-10:45 (채플실)',
      target: '전체',
      currentGrade: undefined,
    },
    {
      category: 'CHAPEL' as const,
      subCategory: '인간',
      field: '인간',
      code: 99001002,
      name: '비전채플',
      professor: '김철홍',
      department: '공통',
      division: null,
      time: '1.0',
      point: '0.5',
      personeel: 0,
      scheduleRoom: '수 10:00-10:45 (채플실)',
      target: '전체',
      currentGrade: undefined,
    },
    {
      category: 'CHAPEL' as const,
      subCategory: '과학',
      field: '과학',
      code: 99001003,
      name: '비전채플',
      professor: '김철홍',
      department: '공통',
      division: null,
      time: '1.0',
      point: '0.5',
      personeel: 0,
      scheduleRoom: '월 13:00-13:45 (채플실)',
      target: '전체',
      currentGrade: undefined,
    },
  ],
};

// ---------------------------------------------------------------------------
// 전공필수
// ---------------------------------------------------------------------------
export const MOCK_MAJOR_REQUIRED = {
  timestamp: '2026-02-06 01:29:27',
  result: [
    {
      category: 'MAJOR_REQUIRED' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어/융선-뉴미디어콘텐츠융합',
      field: '',
      code: 2150445301,
      name: '미디어제작및실습',
      professor: '손금선',
      department: '글로벌미디어학부',
      division: null,
      time: '4.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '화 10:30-11:20 (정보과학관 21501-손금선)\n화 11:30-12:20 (정보과학관 21501-손금선)\n화 12:30-13:20 (정보과학관 21503 (실습실)-손금선)\n화 13:30-14:20 (정보과학관 21503 (실습실)-손금선)',
      target: '1학년 글로벌미디어, 뉴미디어콘텐츠융합',
      currentGrade: undefined,
    },
    {
      category: 'MAJOR_REQUIRED' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어/융선-뉴미디어콘텐츠융합',
      field: '',
      code: 2150445302,
      name: '미디어제작및실습',
      professor: '손금선',
      department: '글로벌미디어학부',
      division: null,
      time: '4.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '금 10:30-11:20 (정보과학관 21501-손금선)\n금 11:30-12:20 (정보과학관 21501-손금선)\n금 12:30-13:20 (정보과학관 21503 (실습실)-손금선)\n금 13:30-14:20 (정보과학관 21503 (실습실)-손금선)',
      target: '1학년 글로벌미디어, 뉴미디어콘텐츠융합',
      currentGrade: undefined,
    },
    {
      category: 'MAJOR_REQUIRED' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어/융선-뉴미디어콘텐츠융합',
      field: '',
      code: 2150445303,
      name: '미디어제작및실습',
      professor: '윤인정',
      department: '글로벌미디어학부',
      division: null,
      time: '4.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '월 15:30-16:20 (정보과학관 21502 (실습실)-윤인정)\n월 16:30-17:20 (정보과학관 21502 (실습실)-윤인정)\n금 13:00-13:50 (정보과학관 21508 (디지털미디어스튜디오)-윤인정)\n금 14:00-14:50 (정보과학관 21508 (디지털미디어스튜디오)-윤인정)',
      target: '1학년 글로벌미디어',
      currentGrade: undefined,
    },
    {
      category: 'MAJOR_REQUIRED' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어/융선-뉴미디어콘텐츠융합',
      field: '',
      code: 2150451601,
      name: '컴퓨터시스템개론',
      professor: '정기철',
      department: '글로벌미디어학부',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '화 09:00-10:15 (정보과학관 21601-정기철)\n금 10:30-11:45 (정보과학관 21601-정기철)',
      target: '1학년 글로벌미디어, 뉴미디어콘텐츠융합',
      currentGrade: undefined,
    },
    {
      category: 'MAJOR_REQUIRED' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어/융선-뉴미디어콘텐츠융합',
      field: '',
      code: 2150451602,
      name: '컴퓨터시스템개론',
      professor: '정기철',
      department: '글로벌미디어학부',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '화 10:30-11:45 (정보과학관 21601-정기철)\n금 09:00-10:15 (정보과학관 21601-정기철)',
      target: '1학년 글로벌미디어, 뉴미디어콘텐츠융합',
      currentGrade: undefined,
    },
    {
      category: 'MAJOR_REQUIRED' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어/융선-뉴미디어콘텐츠융합',
      field: '',
      code: 2150451603,
      name: '컴퓨터시스템개론',
      professor: '정기철',
      department: '글로벌미디어학부',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '수 09:00-10:15 (정보과학관 21601-정기철)\n목 10:30-11:45 (정보과학관 21601-정기철)',
      target: '1학년 글로벌미디어',
      currentGrade: undefined,
    },
    {
      category: 'MAJOR_REQUIRED' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 5010428601,
      name: '프로그래밍2및실습',
      professor: '이강희',
      department: '글로벌미디어학부',
      division: null,
      time: '4.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '월 14:00-14:50 (정보과학관 21508 (디지털미디어스튜디오)-이강희)\n월 15:00-15:50 (정보과학관 21508 (디지털미디어스튜디오)-이강희)\n수 14:00-14:50 (정보과학관 21508 (디지털미디어스튜디오)-이강희)\n수 15:00-15:50 (정보과학관 21508 (디지털미디어스튜디오)-이강희)',
      target: '1학년 글로벌미디어',
      currentGrade: undefined,
      recommendedGrade: 2,
    },
    {
      category: 'MAJOR_REQUIRED' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 5010428602,
      name: '프로그래밍2및실습',
      professor: null,
      department: '글로벌미디어학부',
      division: null,
      time: '4.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '월 10:00-10:50 (정보과학관 21503 (실습실)-)\n월 11:00-11:50 (정보과학관 21503 (실습실)-)\n목 12:00-12:50 (정보과학관 21502 (실습실)-)\n목 13:00-13:50 (정보과학관 21502 (실습실)-)',
      target: '1학년 글로벌미디어',
      currentGrade: undefined,
      recommendedGrade: 2,
    },
    {
      category: 'MAJOR_REQUIRED' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 5010428603,
      name: '프로그래밍2및실습',
      professor: '오경수',
      department: '글로벌미디어학부',
      division: null,
      time: '4.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '화 15:30-16:20 (정보과학관 21502 (실습실)-오경수)\n화 16:30-17:20 (정보과학관 21502 (실습실)-오경수)\n금 15:30-16:20 (정보과학관 21502 (실습실)-오경수)\n금 16:30-17:20 (정보과학관 21502 (실습실)-오경수)',
      target: '1학년 글로벌미디어',
      currentGrade: undefined,
      recommendedGrade: 2,
    },
  ],
};

// ---------------------------------------------------------------------------
// 교양필수
// ---------------------------------------------------------------------------
export const MOCK_GENERAL_REQUIRED = {
  timestamp: '2026-02-06 01:29:45',
  result: [
    {
      category: 'GENERAL_REQUIRED' as const,
      subCategory: null,
      field: '디지털테크놀로지(SW와AI)',
      code: 2150103601,
      name: '[SW와AI]AI개발과실전',
      professor: '노은희',
      department: '교양교육운영팀',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '목 09:00-10:15 (백마관 07402 PC실습실-노은희)\n목 10:30-11:45 (백마관 07402 PC실습실-노은희)',
      target: '1학년 전자공학전공 ,IT융합전공 ,글로벌미디어',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_REQUIRED' as const,
      subCategory: null,
      field: '디지털테크놀로지(SW와AI)',
      code: 2150103603,
      name: '[SW와AI]AI개발과실전',
      professor: '노은희',
      department: '교양교육운영팀',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '월 12:00-13:15 (백마관 07217 (PC실습실)-노은희)\n월 13:30-14:45 (백마관 07217 (PC실습실)-노은희)',
      target: '1학년',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_REQUIRED' as const,
      subCategory: null,
      field: '디지털테크놀로지(SW와AI)',
      code: 2150103604,
      name: '[SW와AI]AI개발과실전',
      professor: '노은희',
      department: '교양교육운영팀',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '목 15:00-16:15 (백마관 07217 (PC실습실)-노은희)\n목 16:30-17:45 (백마관 07217 (PC실습실)-노은희)',
      target: '1학년',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_REQUIRED' as const,
      subCategory: null,
      field: '디지털테크놀로지(SW와AI)',
      code: 2150103440,
      name: '[SW와AI]AI와데이터기초',
      professor: '김완섭',
      department: '교양교육운영팀',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '목 09:00-10:15 (조만식기념관 12402-김완섭)\n목 10:30-11:45 (조만식기념관 12402-김완섭)',
      target: '1학년 전자공학전공 ,IT융합전공 ,글로벌미디어',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_REQUIRED' as const,
      subCategory: null,
      field: '디지털테크놀로지(SW와AI)',
      code: 2150103441,
      name: '[SW와AI]AI와데이터기초',
      professor: '이미향',
      department: '교양교육운영팀',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '목 09:00-10:15 (조만식기념관 12424-이미향)\n목 10:30-11:45 (조만식기념관 12424-이미향)',
      target: '1학년 전자공학전공 ,IT융합전공 ,글로벌미디어',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_REQUIRED' as const,
      subCategory: null,
      field: '디지털테크놀로지(SW와AI)',
      code: 2150103501,
      name: '[SW와AI]AI와머신러닝',
      professor: '봉진숙',
      department: '교양교육운영팀',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '목 09:00-10:15 (진리관 11310 (PC실습실)-봉진숙)\n목 10:30-11:45 (진리관 11310 (PC실습실)-봉진숙)',
      target: '1학년 전자공학전공 ,IT융합전공 ,글로벌미디어',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_REQUIRED' as const,
      subCategory: null,
      field: '디지털테크놀로지(SW와AI)',
      code: 2150103503,
      name: '[SW와AI]AI와머신러닝',
      professor: '봉진숙',
      department: '교양교육운영팀',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '월 12:00-13:15 (백마관 07402 PC실습실-봉진숙)\n월 13:30-14:45 (백마관 07402 PC실습실-봉진숙)',
      target: '1학년',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_REQUIRED' as const,
      subCategory: null,
      field: '품격(인간과성서)',
      code: 2150101903,
      name: '[인간과성서]인류문명과기독교',
      professor: '김태연',
      department: '교양교육운영팀',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom:
        '수 09:00-09:50 (조만식기념관 12328-김태연)\n수 10:00-10:50 (조만식기념관 12328-김태연)',
      target: '1학년 컴퓨터 ,글로벌미디어 ,소프트',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_REQUIRED' as const,
      subCategory: null,
      field: '품격(인간과성서)',
      code: 2150101406,
      name: '[인간과성서]인문학과성서',
      professor: '설충수',
      department: '교양교육운영팀',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '수 09:00-09:50 (진리관 11402-설충수)\n수 10:00-10:50 (진리관 11402-설충수)',
      target: '1학년 컴퓨터 ,글로벌미디어 ,소프트',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_REQUIRED' as const,
      subCategory: null,
      field: '품격(인간과성서)',
      code: 2150102006,
      name: '[인간과성서]현대사회이슈와기독교',
      professor: '김명배',
      department: '교양교육운영팀',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '수 09:00-09:50 (전산관 19327-김명배)\n수 10:00-10:50 (전산관 19327-김명배)',
      target: '1학년 컴퓨터 ,글로벌미디어 ,소프트',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_REQUIRED' as const,
      subCategory: null,
      field: '창의(인문적상상력과소통)',
      code: 2150100303,
      name: '[인문적상상력과소통]고전읽기와상상력',
      professor: '이상명',
      department: '교양교육운영팀',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '수 11:00-11:50 (진리관 11402-이상명)\n수 12:00-12:50 (진리관 11402-이상명)',
      target: '1학년 컴퓨터 ,글로벌미디어 ,소프트',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_REQUIRED' as const,
      subCategory: null,
      field: '창의(인문적상상력과소통)',
      code: 2150100106,
      name: '[인문적상상력과소통]디지털미래세계와소통',
      professor: '박연숙',
      department: '교양교육운영팀',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '수 11:00-11:50 (진리관 11305-박연숙)\n수 12:00-12:50 (진리관 11305-박연숙)',
      target: '1학년 컴퓨터 ,글로벌미디어 ,소프트',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_REQUIRED' as const,
      subCategory: null,
      field: '',
      code: 2150663401,
      name: '한반도평화와통일',
      professor: '조은희',
      department: '교양교육운영팀',
      division: null,
      time: '1.0',
      point: '1.0',
      personeel: 0,
      scheduleRoom: '',
      target: '1학년 인문대 ,법대 ,사회대 ,경통대 ,IT대',
      currentGrade: undefined,
    },
  ],
};

// ---------------------------------------------------------------------------
// 교양선택
// ---------------------------------------------------------------------------
export const MOCK_GENERAL_ELECTIVE = {
  timestamp: '2026-02-06 02:15:00',
  result: [
    {
      category: 'GENERAL_ELECTIVE' as const,
      subCategory: '인간',
      field: '인간・언어',
      code: 1150101101,
      name: '건축학개론',
      professor: '김철홍',
      department: '교양교육운영팀',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '월 10:00-11:15 (형남공학관 30201-김철홍)',
      target: '전체',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_ELECTIVE' as const,
      subCategory: '인간',
      field: '인간・언어',
      code: 1150101201,
      name: '섬김의리더십',
      professor: '김철홍',
      department: '교양교육운영팀',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '수 10:00-11:15 (형남공학관 30201-김철홍)',
      target: '전체',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_ELECTIVE' as const,
      subCategory: '과학',
      field: '과학・기술',
      code: 1150101301,
      name: '일본어입문',
      professor: '김철홍',
      department: '교양교육운영팀',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '월 10:00-11:15 (형남공학관 30201-김철홍)',
      target: '전체',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_ELECTIVE' as const,
      subCategory: '숭실품성교과',
      field: '인성과 리더십',
      code: 1150101401,
      name: '인성과리더십',
      professor: '김철홍',
      department: '교양교육운영팀',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '월 10:00-11:15 (형남공학관 30201-김철홍)',
      target: '전체',
      currentGrade: undefined,
    },
    {
      category: 'GENERAL_ELECTIVE' as const,
      subCategory: '기초역량교과',
      field: '한국어의사소통',
      code: 1150101501,
      name: '한국어의사소통',
      professor: '김철홍',
      department: '교양교육운영팀',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '수 10:00-11:15 (형남공학관 30201-김철홍)',
      target: '전체',
      currentGrade: undefined,
    },
  ],
};

// ---------------------------------------------------------------------------
// 전공선택
// ---------------------------------------------------------------------------
export const MOCK_MAJOR_ELECTIVE = {
  timestamp: '2026-02-06 01:30:10',
  result: [
    {
      category: 'MAJOR_ELECTIVE' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 2150452201,
      name: 'UI/UX디자인',
      professor: '장수진',
      department: '글로벌미디어학부',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '월 09:00-10:15 (정보과학관 21503 (실습실)-장수진)\n수 09:00-10:15 (정보과학관 21503 (실습실)-장수진)',
      target: '2학년 글로벌미디어',
      currentGrade: undefined,
    },
    {
      category: 'MAJOR_ELECTIVE' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 2150452202,
      name: 'UI/UX디자인',
      professor: '장수진',
      department: '글로벌미디어학부',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '화 14:00-15:15 (정보과학관 21503 (실습실)-장수진)\n목 14:00-15:15 (정보과학관 21503 (실습실)-장수진)',
      target: '2학년 글로벌미디어',
      currentGrade: undefined,
    },
    {
      category: 'MAJOR_ELECTIVE' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 2150453101,
      name: '데이터과학기초',
      professor: '김민수',
      department: '글로벌미디어학부',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '월 10:30-11:45 (정보과학관 21601-김민수)\n수 10:30-11:45 (정보과학관 21601-김민수)',
      target: '2학년 글로벌미디어, 뉴미디어콘텐츠융합',
      currentGrade: undefined,
    },
    {
      category: 'MAJOR_ELECTIVE' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 2150453102,
      name: '데이터과학기초',
      professor: '김민수',
      department: '글로벌미디어학부',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '화 09:00-10:15 (정보과학관 21601-김민수)\n금 09:00-10:15 (정보과학관 21601-김민수)',
      target: '2학년 글로벌미디어, 뉴미디어콘텐츠융합',
      currentGrade: undefined,
    },
    {
      category: 'MAJOR_ELECTIVE' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 2150454001,
      name: '웹개발과실습',
      professor: '이강희',
      department: '글로벌미디어학부',
      division: null,
      time: '4.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '월 13:00-13:50 (정보과학관 21508 (디지털미디어스튜디오)-이강희)\n월 14:00-14:50 (정보과학관 21508 (디지털미디어스튜디오)-이강희)\n수 13:00-13:50 (정보과학관 21508 (디지털미디어스튜디오)-이강희)\n수 14:00-14:50 (정보과학관 21508 (디지털미디어스튜디오)-이강희)',
      target: '2학년 글로벌미디어',
      currentGrade: undefined,
    },
    {
      category: 'MAJOR_ELECTIVE' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 2150455001,
      name: '모바일앱개발',
      professor: '오경수',
      department: '글로벌미디어학부',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '화 11:00-12:15 (정보과학관 21502 (실습실)-오경수)\n목 11:00-12:15 (정보과학관 21502 (실습실)-오경수)',
      target: '2학년 글로벌미디어',
      currentGrade: undefined,
    },
    {
      category: 'MAJOR_ELECTIVE' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 2150456001,
      name: '영상제작기술',
      professor: '윤인정',
      department: '글로벌미디어학부',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '월 15:30-16:45 (정보과학관 21508 (디지털미디어스튜디오)-윤인정)\n금 15:30-16:45 (정보과학관 21508 (디지털미디어스튜디오)-윤인정)',
      target: '2학년 글로벌미디어, 뉴미디어콘텐츠융합',
      currentGrade: undefined,
    },
  ],
};

// ---------------------------------------------------------------------------
// 복수전공 (이수한 과목에 currentGrade 포함)
// ---------------------------------------------------------------------------
export const MOCK_DOUBLE_MAJOR = {
  timestamp: '2026-02-06 01:30:20',
  result: [
    {
      category: 'DOUBLE_MAJOR' as const,
      subCategory: '복선-컴퓨터과학',
      field: '',
      code: 3010201001,
      name: '프로그래밍개론',
      professor: '최현석',
      department: '컴퓨터과학학과',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom: '월 09:00-10:15 (진리관 11310-최현석)\n수 09:00-10:15 (진리관 11310-최현석)',
      target: '1학년 컴퓨터과학',
      currentGrade: 'B+',
    },
    {
      category: 'DOUBLE_MAJOR' as const,
      subCategory: '복선-컴퓨터과학',
      field: '',
      code: 3010201002,
      name: '프로그래밍개론',
      professor: '최현석',
      department: '컴퓨터과학학과',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom: '화 10:30-11:45 (진리관 11310-최현석)\n목 10:30-11:45 (진리관 11310-최현석)',
      target: '1학년 컴퓨터과학',
      currentGrade: undefined,
    },
    {
      category: 'DOUBLE_MAJOR' as const,
      subCategory: '복선-컴퓨터과학',
      field: '',
      code: 3010202001,
      name: '자료구조',
      professor: '박영대',
      department: '컴퓨터과학학과',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom: '월 14:00-15:15 (진리관 11305-박영대)\n금 14:00-15:15 (진리관 11305-박영대)',
      target: '2학년 컴퓨터과학',
      currentGrade: 'A-',
    },
    {
      category: 'DOUBLE_MAJOR' as const,
      subCategory: '복선-컴퓨터과학',
      field: '',
      code: 3010202002,
      name: '자료구조',
      professor: '박영대',
      department: '컴퓨터과학학과',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom: '화 09:00-10:15 (진리관 11306-박영대)\n금 09:00-10:15 (진리관 11306-박영대)',
      target: '2학년 컴퓨터과학',
      currentGrade: undefined,
    },
    {
      category: 'DOUBLE_MAJOR' as const,
      subCategory: '복선-컴퓨터과학',
      field: '',
      code: 3010203001,
      name: '운영체제',
      professor: '한영진',
      department: '컴퓨터과학학과',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom: '수 11:00-12:15 (진리관 11402-한영진)\n목 11:00-12:15 (진리관 11402-한영진)',
      target: '3학년 컴퓨터과학',
      currentGrade: undefined,
    },
  ],
};

// ---------------------------------------------------------------------------
// 부전공 (이수한 과목에 currentGrade 포함)
// ---------------------------------------------------------------------------
export const MOCK_MINOR = {
  timestamp: '2026-02-06 01:30:30',
  result: [
    {
      category: 'MINOR' as const,
      subCategory: '부선-일본어',
      field: '',
      code: 4020101001,
      name: '일본어기초1',
      professor: '田中美香',
      department: '일본어학과',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom:
        '월 11:00-11:50 (백마관 07116-田中美香)\n수 11:00-11:50 (백마관 07116-田中美香)',
      target: '1학년 이상',
      currentGrade: 'A',
    },
    {
      category: 'MINOR' as const,
      subCategory: '부선-일본어',
      field: '',
      code: 4020101002,
      name: '일본어기초1',
      professor: '김유진',
      department: '일본어학과',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '화 13:00-13:50 (백마관 07218-김유진)\n목 13:00-13:50 (백마관 07218-김유진)',
      target: '1학년 이상',
      currentGrade: undefined,
    },
    {
      category: 'MINOR' as const,
      subCategory: '부선-일본어',
      field: '',
      code: 4020102001,
      name: '일본어기초2',
      professor: '田中美香',
      department: '일본어학과',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom:
        '월 13:00-13:50 (백마관 07116-田中美香)\n수 13:00-13:50 (백마관 07116-田中美香)',
      target: '1학년 이상',
      currentGrade: undefined,
    },
    {
      category: 'MINOR' as const,
      subCategory: '부선-일본어',
      field: '',
      code: 4020103001,
      name: '일본어회화',
      professor: '김유진',
      department: '일본어학과',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '화 15:00-15:50 (백마관 07119-김유진)\n목 15:00-15:50 (백마관 07119-김유진)',
      target: '2학년 이상',
      currentGrade: undefined,
    },
  ],
};

// ---------------------------------------------------------------------------
// 교직이수
// ---------------------------------------------------------------------------
export const MOCK_TEACHING_CERTIFICATE = {
  timestamp: '2026-02-06 01:30:40',
  result: [
    {
      category: 'TEACHING_CERTIFICATE' as const,
      subCategory: null,
      field: '',
      code: 6010101001,
      name: '교육학개론',
      professor: '신영석',
      department: '사범대학 교육학과',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom: '월 10:30-11:45 (백마관 07402-신영석)\n수 10:30-11:45 (백마관 07402-신영석)',
      target: '교직이수 학생',
      currentGrade: 'B',
    },
    {
      category: 'TEACHING_CERTIFICATE' as const,
      subCategory: null,
      field: '',
      code: 6010102001,
      name: '교육심리학',
      professor: '박정현',
      department: '사범대학 교육학과',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '수 14:00-15:15 (백마관 07217-박정현)',
      target: '교직이수 학생',
      currentGrade: undefined,
    },
    {
      category: 'TEACHING_CERTIFICATE' as const,
      subCategory: null,
      field: '',
      code: 6010103001,
      name: '교수법과평가',
      professor: '신영석',
      department: '사범대학 교육학과',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '목 09:00-10:15 (백마관 07119-신영석)',
      target: '교직이수 학생',
      currentGrade: undefined,
    },
    {
      category: 'TEACHING_CERTIFICATE' as const,
      subCategory: null,
      field: '',
      code: 6010104001,
      name: '교육과학과기술',
      professor: '박정현',
      department: '사범대학 교육학과',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '금 11:00-12:15 (백마관 07218-박정현)',
      target: '교직이수 학생',
      currentGrade: undefined,
    },
  ],
};

// ---------------------------------------------------------------------------
// 재수강 (반드시 currentGrade 포함 — 이전 성적이 낮아 재수강하는 과목)
// ---------------------------------------------------------------------------
export const MOCK_RETAKE = {
  timestamp: '2026-02-06 01:30:50',
  result: [
    {
      category: 'RETAKE' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 5010318601,
      name: '프로그래밍1및실습',
      professor: '이강희',
      department: '글로벌미디어학부',
      division: null,
      time: '4.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '월 09:00-09:50 (정보과학관 21508 (디지털미디어스튜디오)-이강희)\n월 10:00-10:50 (정보과학관 21508 (디지털미디어스튜디오)-이강희)\n수 09:00-09:50 (정보과학관 21508 (디지털미디어스튜디오)-이강희)\n수 10:00-10:50 (정보과학관 21508 (디지털미디어스튜디오)-이강희)',
      target: '1학년 글로벌미디어',
      currentGrade: 'D',
    },
    {
      category: 'RETAKE' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 5010318602,
      name: '프로그래밍1및실습',
      professor: '오경수',
      department: '글로벌미디어학부',
      division: null,
      time: '4.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '화 09:00-09:50 (정보과학관 21502 (실습실)-오경수)\n화 10:00-10:50 (정보과학관 21502 (실습실)-오경수)\n목 09:00-09:50 (정보과학관 21502 (실습실)-오경수)\n목 10:00-10:50 (정보과학관 21502 (실습실)-오경수)',
      target: '1학년 글로벌미디어',
      currentGrade: 'D',
    },
    {
      category: 'RETAKE' as const,
      subCategory: null,
      field: '품격(인간과성서)',
      code: 2150101405,
      name: '[인간과성서]인문학과성서',
      professor: '김옥주',
      department: '교양교육운영팀',
      division: null,
      time: '2.0',
      point: '2.0',
      personeel: 0,
      scheduleRoom: '수 09:00-09:50 (진리관 11517-김옥주)\n수 10:00-10:50 (진리관 11517-김옥주)',
      target: '1학년 컴퓨터 ,글로벌미디어 ,소프트',
      currentGrade: 'C-',
    },
  ],
};

// ---------------------------------------------------------------------------
// 선수학습 (수강 전 이수해야 하는 과목, currentGrade 포함)
// ---------------------------------------------------------------------------
export const MOCK_MAJOR_PREREQUISITE = {
  timestamp: '2026-02-06 01:31:00',
  result: [
    {
      category: 'MAJOR_PREREQUISITE' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 5010318501,
      name: '프로그래밍1및실습',
      professor: '이강희',
      department: '글로벌미디어학부',
      division: null,
      time: '4.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '월 09:00-09:50 (정보과학관 21508-이강희)\n월 10:00-10:50 (정보과학관 21508-이강희)\n수 09:00-09:50 (정보과학관 21508-이강희)\n수 10:00-10:50 (정보과학관 21508-이강희)',
      target: '1학년 글로벌미디어',
      currentGrade: 'B+',
    },
    {
      category: 'MAJOR_PREREQUISITE' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 2150445201,
      name: '미디어이론및실습',
      professor: '손금선',
      department: '글로벌미디어학부',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '화 09:00-10:15 (정보과학관 21501-손금선)\n금 09:00-10:15 (정보과학관 21501-손금선)',
      target: '1학년 글로벌미디어',
      currentGrade: 'A-',
    },
    {
      category: 'MAJOR_PREREQUISITE' as const,
      subCategory: '복선-글로벌미디어/부선-글로벌미디어',
      field: '',
      code: 2150445202,
      name: '미디어이론및실습',
      professor: '손금선',
      department: '글로벌미디어학부',
      division: null,
      time: '3.0',
      point: '3.0',
      personeel: 0,
      scheduleRoom:
        '월 14:00-15:15 (정보과학관 21501-손금선)\n수 14:00-15:15 (정보과학관 21501-손금선)',
      target: '1학년 글로벌미디어',
      currentGrade: undefined,
    },
  ],
};
