import { type TimetableSuggestResponseInputType } from '@/schemas/timetableSuggestSchema';

export const MOCK_TIMETABLE_SUGGEST: TimetableSuggestResponseInputType = {
  timestamp: '2026-02-06 12:00:00',
  result: {
    timetable: {
      timetableId: 1,
      tag: '기본 태그',
      score: null,
      totalPoint: 21,
      courses: [
        {
          category: 'MAJOR_REQUIRED',
          subCategory: '컴퓨터학부',
          field: null,
          code: 2150545501,
          name: '컴퓨터학개론',
          professor: '홍길동',
          department: '컴퓨터학부',
          division: null,
          time: '3.0',
          point: '3.0',
          personeel: 60,
          scheduleRoom: '월 11:00-12:15 (정보과학관 101)',
          target: '1학년 컴퓨터학부',
          recommendedGrade: 1,
          courseTimes: [{ week: '월', start: '11:00', end: '12:15', classroom: '정보과학관 101' }],
        },
        {
          category: 'MAJOR_REQUIRED',
          subCategory: '컴퓨터학부',
          field: null,
          code: 2150545502,
          name: '자료구조',
          professor: '김교수',
          department: '컴퓨터학부',
          division: null,
          time: '3.0',
          point: '3.0',
          personeel: 60,
          scheduleRoom: '화 11:00-12:15 (정보과학관 102)',
          target: '2학년 컴퓨터학부',
          recommendedGrade: 2,
          courseTimes: [{ week: '화', start: '11:00', end: '12:15', classroom: '정보과학관 102' }],
        },
        {
          category: 'MAJOR_REQUIRED',
          subCategory: '컴퓨터학부',
          field: null,
          code: 2150545503,
          name: '컴퓨터구조2',
          professor: '이교수',
          department: '컴퓨터학부',
          division: null,
          time: '3.0',
          point: '3.0',
          personeel: 60,
          scheduleRoom: '목 11:00-12:15 (정보과학관 103)',
          target: '2학년 컴퓨터학부',
          recommendedGrade: 2,
          courseTimes: [{ week: '목', start: '11:00', end: '12:15', classroom: '정보과학관 103' }],
        },
        {
          category: 'GENERAL_REQUIRED',
          subCategory: null,
          field: '수학',
          code: 2150225101,
          name: '선형대수',
          professor: '박교수',
          department: '교양교육운영팀',
          division: null,
          time: '3.0',
          point: '3.0',
          personeel: 80,
          scheduleRoom: '목 11:00-12:15 (백마관 201)',
          target: '전학년',
          recommendedGrade: 2,
          courseTimes: [{ week: '목', start: '11:00', end: '12:15', classroom: '백마관 201' }],
        },
        {
          category: 'MAJOR_ELECTIVE',
          subCategory: '컴퓨터학부',
          field: null,
          code: 2150143401,
          name: '운영체제',
          professor: '최교수',
          department: '컴퓨터학부',
          division: null,
          time: '3.0',
          point: '3.0',
          personeel: 60,
          scheduleRoom: '금 11:00-12:15 (정보과학관 104)',
          target: '3학년 컴퓨터학부',
          recommendedGrade: 3,
          courseTimes: [{ week: '금', start: '11:00', end: '12:15', classroom: '정보과학관 104' }],
        },
      ],
    },
    notices: [
      {
        id: 'notice-1',
        title: '[컴퓨터구조2] or [선형대수] 삭제',
        description:
          '[컴퓨터구조2]와 [선형대수]와 강의 시간이 겹쳐서 시간표를 생성할 수 없어요. 어떤 과목을 삭제할까요?',
        actions: [
          {
            type: 'REMOVE',
            courseCode: 2150545503,
            courseName: '컴퓨터구조2',
            label: '[컴퓨터구조2] 삭제',
          },
          {
            type: 'REMOVE',
            courseCode: 2150225101,
            courseName: '선형대수',
            label: '[선형대수] 삭제',
          },
        ],
        selectionMode: 'single',
      },
    ],
    suggestions: [
      {
        id: 'suggestion-1',
        title: '[컴퓨터구조2] → [컴퓨터학개론] 변경',
        description:
          '[컴퓨터구조2]를 [컴퓨터학개론]으로 변경하면 월공강을 만들 수 있어요! 변경할까요?',
        actions: [
          {
            type: 'REPLACE',
            fromCourseCode: 2150545503,
            fromCourseName: '컴퓨터구조2',
            toCourseCode: 2150545501,
            toCourseName: '컴퓨터학개론',
            label: '[컴퓨터구조2]를 [컴퓨터학개론]으로 변경',
          },
        ],
        selectionMode: 'single',
      },
    ],
  },
};
