name: 😡 [Main] Deploy Production
on:
  push:
    branches: [main]

jobs:
  build_and_deploy_production:
    uses: ./.github/workflows/build-and-deploy.yml
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      VITE_MIXPANEL_TOKEN: ${{ secrets.VITE_MIXPANEL_TOKEN }}
      VITE_CHANNEL_TALK_PLUGIN_KEY: ${{ secrets.VITE_CHANNEL_TALK_PLUGIN_KEY }}
      VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
      VITE_SENTRY_AUTH_TOKEN: ${{ secrets.VITE_SENTRY_AUTH_TOKEN }}
    with:
      STAGE: 'prod'
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      CLOUDFLARE_PROJECT_NAME: 'soongpt-web'
